name: adam_family
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  modal_progress_hud_nsn: ^0.3.0
  curved_navigation_bar: ^1.0.3
  fab_circular_menu: ^1.0.2
  liquid_swipe: ^3.0.0
  cupertino_icons: ^1.0.5
  line_awesome_flutter: ^2.0.0
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  firebase_auth: ^4.0.2
  firebase_auth_web: ^5.1.1
  firebase_core: ^2.1.1
  firebase_core_web: ^2.0.1
  firebase_analytics: ^10.0.3
  firebase_database: ^10.0.3
  cloud_firestore: ^4.0.3
  google_sign_in: ^5.4.2
  google_sign_in_web: ^0.10.2
  flutter_facebook_auth: ^5.0.6
  rename: ^2.0.1
  riverpod: ^2.1.1
  hexcolor: ^3.0.1
  font_awesome_flutter: ^10.2.1
  flutter_native_splash: ^2.2.16
  smooth_page_indicator: ^1.0.0+2
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.1
  flutterfire_cli: ^0.2.7
  url_launcher: ^6.1.7
  flutter_launcher_icons: ^0.11.0
  country_codes: ^2.2.0
  fl_country_code_picker: ^0.0.4
  provider: ^6.0.4
  get: ^4.6.5
  get_storage: ^2.0.3
  pinput: ^2.2.16
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Tree-icon-app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/Tree-icon-app.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/Tree-icon-app.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/Tree-icon-app.png"


  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages